CREATE TABLE TACGIA (
    MATG CHAR(5) PRIMARY KEY,
    HOTEN VARCHAR(20),
    DIACHI VARCHAR(50),
    NGSINH SMALLDATETIME,
    SODT VARCHAR(15)
)

CREATE TABLE SACH(
    MASACH CHAR(5) PRIMARY KEY,
    TENSACH VARCHAR(25),
    THELOAI VARCHAR(25)
)

CREATE TABLE TACGIA_SACH(
    MATG CHAR(5),
    MASACH CHAR(5)
    CONSTRAINT TACGIASACH_MATG_MASACH_PK PRIMARY KEY (MATG,MASACH)
)


ALTER TABLE TACGIA_SACH ADD 
    CONSTRAINT TGS_MASACH_FK FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
    CONSTRAINT TGS_MATG_FK FOREIGN KEY(MATG) REFERENCES TACGIA(MATG)


CREATE TABLE PHATHANH(
    MAPH CHAR(5) PRIMARY KEY,
    MASACH CHAR(5),
    NGAYPH SMALLDATETIME,
    SOLUONG INT,
    NHAXUATBAN VARCHAR(20)
)

ALTER TABLE PHATHANH ADD 
    CONSTRAINT PH_MASACH_FK FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)


-- 2.1
GO
CREATE TRIGGER TACGIA_TRIGGER ON TACGIA FOR UPDATE AS 
BEGIN
    IF EXISTS (
        SELECT *
        FROM inserted I , PHATHANH PH, TACGIA_SACH TGS 
        WHERE (I.MATG = TGS.MATG AND PH.MASACH = TGS.MASACH ) AND (PH.NGAYPH< I.NGSINH) )
        BEGIN
            RAISERROR('GIA TRI NGAY PHAT HANH VA NGAY SINH KHONG HOP LE!!!',0,1);
            ROLLBACK TRANSACTION
        END 
        ELSE 
        BEGIN
            PRINT('DU LIEU DUOC THAY DOI!!!');
        END
END



GO
CREATE TRIGGER PHATHANH_TRIGGER ON PHATHANH  FOR UPDATE,INSERT AS 
BEGIN 
    IF EXISTS (
        SELECT *
        FROM inserted I , TACGIA TG, TACGIA_SACH TGS 
        WHERE (TG.MATG = TGS.MATG AND I.MASACH = TGS.MASACH ) AND (I.NGAYPH < TG.NGSINH) )
        BEGIN
            RAISERROR('GIA TRI NGAY PHAT HANH VA NGAY SINH KHONG HOP LE!!!',0,1);
        END 
        ELSE 
        BEGIN
            PRINT('DU LIEU DUOC THAY DOI!!!');
        END
END


--2.2

GO
CREATE TRIGGER SACH_TRIGGER ON SACH FOR UPDATE AS 
BEGIN 
    IF EXISTS (
        SELECT *
        FROM inserted S,PHATHANH PH 
        WHERE S.MASACH = PH.MASACH AND S.THELOAI = 'GIAO KHOA' AND PH.NHAXUATBAN != 'GIAODUC'
    )
    BEGIN 
        RAISERROR('DU LIEU SAI!!!',0,1)
        ROLLBACK TRANSACTION
    END
    ELSE 
    BEGIN 
        PRINT('THEM DU LIEU THANH CONG!!!');
    END 
END    


GO 
CREATE TRIGGER PHATHANH_TRIGGER ON PHATHANH FOR UPDATE,INSERT AS 
BEGIN 
    IF EXISTS(
        SELECT *
        FROM inserted PH,SACH S 
        WHERE PH.MASACH = S.MASACH AND (S.THELOAI = 'GIAO KHOA' AND PH.NHAXUATBAN != 'GIAO DUC')
    )
    BEGIN 
        RAISERROR('DU LIEU SAI!!!',0,1)
        ROLLBACK TRANSACTION
    END
    ELSE 
    BEGIN 
        PRINT('THEM DU LIEU THANH CONG!!!');
    END 
END



--3.1
SELECT TG.MATG,HOTEN,SODT
FROM TACGIA TG,SACH S,TACGIA_SACH TGS , PHATHANH PH
WHERE (TG.MATG = TGS.MATG AND S.MASACH = TGS.MASACH AND PH.MASACH = S.MASACH) AND S.THELOAI = 'VANHOC' AND PH.NHAXUATBAN = 'TRE'

-- 3.2
SELECT TOP 1 WITH TIES PH.NHAXUATBAN,COUNT(S.THELOAI) AS SOLUONGTHELOAI
FROM SACH S, PHATHANH PH 
WHERE S.MASACH = PH.MASACH 
GROUP BY NHAXUATBAN
ORDER BY SOLUONGTHELOAI DESC

--3.3

SELECT NHAXUATBAN,TACGIA.MATG,TACGIA.HOTEN,COUNT(MAPH) AS SOLUONGPH
FROM TACGIA,PHATHANH C,TACGIA_SACH
WHERE TACGIA.MATG = TACGIA_SACH.MATG AND TACGIA_SACH.MASACH = C.MASACH 
GROUP BY NHAXUATBAN,TACGIA.MATG,TACGIA.HOTEN 
HAVING COUNT(MAPH) >= ALL (
        SELECT COUNT(MAPH) AS SOLUONGPH
        FROM TACGIA,PHATHANH B,TACGIA_SACH
        WHERE TACGIA.MATG = TACGIA_SACH.MATG AND TACGIA_SACH.MASACH = B.MASACH 
        GROUP BY NHAXUATBAN,TACGIA.MATG,TACGIA.HOTEN
        HAVING B.NHAXUATBAN = C.NHAXUATBAN 
)