USE GX02


CREATE TABLE THANHVIEN (
    MATV CHAR(6) PRIMARY KEY,
    HOTEN VARCHAR(30),
    SODT VARCHAR(15),
    CMND VARCHAR(15),
    LOAITV VARCHAR(15),
)

GO
SET DATEFORMAT DMY 
INSERT INTO THANHVIEN(MATV,HOTEN,SODT,CMND,LOAITV) VALUES ('TV1101','Thóng Lai Bâng','0776665544','261027101472','Lâu dài')
INSERT INTO THANHVIEN(MATV,HOTEN,SODT,CMND,LOAITV) VALUES ('TV1102','Nguyễn Công Vinh','0901231415','217465798','Thường')
INSERT INTO THANHVIEN(MATV,HOTEN,SODT,CMND,LOAITV) VALUES ('TV1103','Trịnh Đào Tiến','0765004321','271002717694','Ngắn hạn')


CREATE TABLE VITRI (
    MAVT CHAR(7) PRIMARY KEY,
    TANG VARCHAR(3),
    HANG INT,
    COT INT ,
    TRANGTHAI VARCHAR(10) 
)

GO
INSERT INTO VITRI(MAVT,TANG,HANG,COT,TRANGTHAI) VALUES ('VTG2001','G2',14,25,'Trống')
INSERT INTO VITRI(MAVT,TANG,HANG,COT,TRANGTHAI) VALUES ('VTG1016','G1',7,7,'Có xe')
INSERT INTO VITRI(MAVT,TANG,HANG,COT,TRANGTHAI) VALUES ('VTG2109','G2',38,16,'Có xe')



CREATE TABLE DANGKY(
    SODK CHAR(8) PRIMARY KEY,
    MATV CHAR(6),
    NGDK SMALLDATETIME,
    THOIHAN SMALLDATETIME,
)
GO
INSERT INTO DANGKY(SODK,MATV,NGDK,THOIHAN) VALUES ('DK01efgs','TV1101','01/06/2020','31/10/2020')
INSERT INTO DANGKY(SODK,MATV,NGDK,THOIHAN) VALUES ('DKa810d2','TV1102','01/12/2020','30/04/2021'
)
INSERT INTO DANGKY(SODK,MATV,NGDK,THOIHAN) VALUES ('DKjw02jf','TV1101','01/11/2020','31/03/2021')





SELECT *  
FROM DANGKY


ALTER TABLE DANGKY ADD 
    CONSTRAINT DANGKY_MATV_FK FOREIGN KEY(MATV) REFERENCES THANHVIEN(MATV)




CREATE TABLE GUIXE (
    SODK CHAR(8),
    MAVT CHAR(7),
    NGGUI SMALLDATETIME
    CONSTRAINT GUIXE_SODK_MATV_NGGUI PRIMARY KEY(SODK,MAVT,NGGUI)
)

ALTER TABLE GUIXE ADD 
    CONSTRAINT GUIXE_SODK_FK FOREIGN KEY(SODK) REFERENCES DANGKY(SODK),
    CONSTRAINT GUIXE_MAVT_FK FOREIGN KEY(MAVT) REFERENCES VITRI(MAVT)

GO
INSERT INTO GUIXE(SODK,MAVT,NGGUI) VALUES ('DKa810d2','VTG2001',24/12/2020)
INSERT INTO GUIXE(SODK,MAVT,NGGUI) VALUES ('DKa810d2','VTG1016',21/12/2020)
INSERT INTO GUIXE(SODK,MAVT,NGGUI) VALUES ('DKjw02jf','VTG2109',12/12/2020)


-- 3 trigger 1 2 cách
GO 
CREATE TRIGGER DANGKY_TRIGGER ON DANGKY FOR UPDATE,INSERT 
AS  
BEGIN 
    IF EXISTS(
        SELECT *
        FROM inserted I 
        WHERE (MONTH(I.NGDK) - MONTH(I.THOIHAN) > 2) OR (YEAR(I.NGDK) > YEAR(I.THOIHAN)) OR (DAY(I.NGDK) > DAY(I.THOIHAN))
    )
    BEGIN 
        RAISERROR('Ngày đăng ký phải nhỏ hơn thời điểm hết hạn ít nhất hai tháng',0,1)
        ROLLBACK TRANSACTION
    END 
    ELSE  
    BEGIN 
        PRINT('SUCCESSFULLY')
    END
END

GO 
CREATE TRIGGER DANGKY_TRIGGER2 ON DANGKY FOR UPDATE,INSERT 
AS  
BEGIN 
    IF EXISTS(
        SELECT *
        FROM inserted I 
        WHERE (SELECT  DATEDIFF(DAY,I.THOIHAN,I.NGDK)) > 60
    )
    BEGIN 
        RAISERROR('Ngày đăng ký phải nhỏ hơn thời điểm hết hạn ít nhất hai tháng',0,1)
        ROLLBACK TRANSACTION
    END 
    ELSE  
    BEGIN 
        PRINT('SUCCESSFULLY')
    END
END


-- 4 trigger 2 

GO 
CREATE TRIGGER DANGKY_TRIGGER3 ON DANGKY FOR UPDATE,INSERT 
AS  
BEGIN 
   DECLARE @SODK CHAR(8), @THOIHAN SMALLDATETIME
   SELECT @SODK = SODK , @THOIHAN = THOIHAN 
   FROM DANGKY
   IF EXISTS(
       SELECT *
       FROM inserted I 
       WHERE I.SODK = @SODK AND I.NGDK < THOIHAN 
   )
   BEGIN 
        RAISERROR('TÀI KHOẢN BẠN CHƯA HẾT HẠN',0,1)
        ROLLBACK TRANSACTION
   END 
   BEGIN
        PRINT('SUCCESSFULLY')    
   END
END

--5 
GO
SELECT VITRI.MAVT
FROM VITRI,THANHVIEN,GUIXE,DANGKY
WHERE (VITRI.MAVT = GUIXE.MAVT AND DANGKY.SODK = GUIXE.SODK AND THANHVIEN.MATV = DANGKY.MATV ) AND THANHVIEN.LOAITV='Ngắn hạn'
ORDER BY GUIXE.NGGUI

--6 
SELECT  TOP 1 WITH TIES  VITRI.TANG,COUNT(GUIXE.SODK) AS SOLANGUIXE
FROM    VITRI,THANHVIEN,GUIXE,DANGKY
WHERE (VITRI.MAVT = GUIXE.MAVT AND DANGKY.SODK = GUIXE.SODK AND THANHVIEN.MATV = DANGKY.MATV ) AND THANHVIEN.LOAITV='Lâu dài'
GROUP BY VITRI.TANG
ORDER BY SOLANGUIXE 

--7 
SELECT DISTINCT MONTH(DANGKY.NGDK),DANGKY.SODK
FROM DANGKY,THANHVIEN,GUIXE 
WHERE (DANGKY.SODK = GUIXE.SODK AND THANHVIEN.MATV = DANGKY.MATV ) AND 
(YEAR(DANGKY.NGDK)=2020) AND THANHVIEN.LOAITV='Thường' 
INTERSECT 
SELECT DISTINCT MONTH(DANGKY.NGDK),DANGKY.SODK
FROM DANGKY,THANHVIEN,GUIXE 
WHERE (DANGKY.SODK = GUIXE.SODK AND THANHVIEN.MATV = DANGKY.MATV ) AND 
(YEAR(DANGKY.NGDK)=2020) AND THANHVIEN.LOAITV='Ngắn hạn' 

--8   
SELECT MAVT,TANG,HANG,COT,TRANGTHAI
FROM VITRI
WHERE NOT EXISTS(
    SELECT *
    FROM THANHVIEN 
    WHERE THANHVIEN.LOAITV='Lâu dài' AND NOT EXISTS( 
        SELECT * 
        FROM  DANGKY,GUIXE 
        WHERE VITRI.MAVT = GUIXE.MAVT AND THANHVIEN.MATV = DANGKY.MATV AND DANGKY.SODK = GUIXE.SODK
    )
)